apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: musicapi
  name: musicapi
  namespace: music-ns
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: musicapi
status:
  loadBalancer: {}
