apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  hostPath:
    path: "/opt/data/mysql"
